const RABBITMQ_HOST = process.env.RABBITMQ_HOST;
const RABBITMQ_USERNAME = process.env.RABBITMQ_USERNAME;
const RABBITMQ_PASSWORD = process.env.RABBITMQ_PASSWORD;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = process.env.REDIS_PORT;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
const ZOHO_NAME = process.env.ZOHO_NAME;
const ZOHO_HOST = process.env.ZOHO_HOST;
const ZOHO_PORT = process.env.ZOHO_PORT;
const ZOHO_SECURE = process.env.ZOHO_SECURE;
const ZOHO_USERNAME = process.env.ZOHO_USERNAME;
const ZOHO_PASSWORD = process.env.ZOHO_PASSWORD;

module.exports = {
  RABBITMQ_HOST,
  RABBITMQ_USERNAME,
  RABBITMQ_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  ZOHO_NAME,
  ZOHO_HOST,
  ZOHO_PORT,
  ZOHO_SECURE,
  ZOHO_USERNAME,
  ZOHO_PASSWORD,
};
